/**
 * Wavefront OBJ with an MTL beside it. One group per material, so a viewer
 * that reads MTL shows the base colours; the procedural pattern is not in an
 * OBJ (no vertex colours in the format), the GLB has it.
 */
import { albedo } from "../sdf/materials.js";
import type { Mesh } from "../mesh/mesh.js";

function f(v: number): string {
  return Number.isInteger(v) ? String(v) : v.toFixed(5).replace(/0+$/, "").replace(/\.$/, "");
}

/**
 * With `uv` (glTF convention, v down) and `textureFile`, `vt` lines are
 * written with v flipped to OBJ's bottom-up convention and every material
 * gets `map_Kd`.
 */
export function toObj(mesh: Mesh, name: string, mtlFile: string, uv?: Float32Array, textureFile?: string): { obj: string; mtl: string } {
  const lines: string[] = [`# ${name}, generated by aixle`, `mtllib ${mtlFile}`, `o ${name}`];
  const p = mesh.positions, nrm = mesh.normals;
  for (let i = 0; i < p.length; i += 3) lines.push(`v ${f(p[i])} ${f(p[i + 1])} ${f(p[i + 2])}`);
  if (uv) for (let i = 0; i < uv.length; i += 2) lines.push(`vt ${f(uv[i])} ${f(1 - uv[i + 1])}`);
  for (let i = 0; i < nrm.length; i += 3) lines.push(`vn ${f(nrm[i])} ${f(nrm[i + 1])} ${f(nrm[i + 2])}`);
  // Group triangles by the material of their first vertex.
  const groups = new Map<number, number[]>();
  const ix = mesh.indices;
  for (let t = 0; t < ix.length; t += 3) {
    const m = mesh.materialIndex[ix[t]];
    let g = groups.get(m);
    if (!g) groups.set(m, (g = []));
    g.push(t);
  }
  for (const [m, tris] of groups) {
    lines.push(`g ${mesh.materials[m].name}`, `usemtl ${mtlName(mesh, m)}`);
    for (const t of tris) {
      const a = ix[t] + 1, b = ix[t + 1] + 1, c = ix[t + 2] + 1;
      lines.push(uv ? `f ${a}/${a}/${a} ${b}/${b}/${b} ${c}/${c}/${c}` : `f ${a}//${a} ${b}//${b} ${c}//${c}`);
    }
  }
  const mtl: string[] = [`# materials for ${name}`];
  mesh.materials.forEach((mat, i) => {
    const c = mat.color;
    mtl.push(
      `newmtl ${mtlName(mesh, i)}`,
      `Kd ${f(c[0])} ${f(c[1])} ${f(c[2])}`,
      `Ka ${f(c[0] * 0.2)} ${f(c[1] * 0.2)} ${f(c[2] * 0.2)}`,
      `Ks ${f(0.2 + mat.metal * 0.6)} ${f(0.2 + mat.metal * 0.6)} ${f(0.2 + mat.metal * 0.6)}`,
      `Ns ${f(Math.round(10 + (1 - mat.rough) * 200))}`,
      `illum 2`,
      ...(textureFile ? [`map_Kd ${textureFile}`] : []),
      "",
    );
  });
  return { obj: lines.join("\n") + "\n", mtl: mtl.join("\n") };
}

function mtlName(mesh: Mesh, i: number): string {
  return `${mesh.materials[i].name.replace(/[^A-Za-z0-9_]/g, "_")}_${i}`;
}

export { albedo };
