/**
 * The GitHub Pages build's two generated pieces.
 *
 *   npm run pages:gallery    writes docs/gallery.md from the committed renders (committed too)
 *   npm run pages:viewers    renders a self-contained GLB viewer page per model into
 *                            .vitepress/public/viewers/<name>.html (not committed; heavy)
 *
 * The gallery lists every example and every dogfooding model with its
 * beauty render, its sheet, its program and its viewer, so the site shows
 * what the tool makes without anyone hand-editing a page.
 */
import { copyFileSync, existsSync, mkdirSync, readdirSync, readFileSync, rmSync, statSync, writeFileSync } from "node:fs";
import { dirname, join, resolve } from "node:path";
import { tmpdir } from "node:os";
import { fileURLToPath } from "node:url";
import { run } from "../src/pipeline.js";

const ROOT = resolve(dirname(fileURLToPath(import.meta.url)), "..");

interface Model {
  name: string;
  /** Repo-relative path of the program. */
  program: string;
  /** Repo-relative folder of its renders. */
  renders: string;
  /** First comment line of the program, as a caption. */
  caption: string;
  /** Repo-relative report, for dogfood models. */
  report?: string;
}

function caption(file: string): string {
  const first = readFileSync(file, "utf8").split("\n").find((l) => l.startsWith("#")) ?? "";
  return first.replace(/^#\s*/, "").trim();
}

function examples(): Model[] {
  const dir = resolve(ROOT, "examples");
  return readdirSync(dir)
    .filter((f) => f.endsWith(".aix"))
    .sort()
    .map((f) => ({ name: f.replace(/\.aix$/, ""), program: `examples/${f}`, renders: "examples/renders", caption: caption(join(dir, f)) }));
}

function dogfood(): Model[] {
  const dir = resolve(ROOT, "dogfood");
  const out: Model[] = [];
  for (const round of readdirSync(dir).filter((d) => d.startsWith("round-")).sort()) {
    for (const f of readdirSync(join(dir, round)).filter((x) => x.endsWith(".aix") && !x.endsWith("_probe.aix")).sort()) {
      const name = f.replace(/\.aix$/, "");
      const report = `dogfood/${round}/${name}.report.md`;
      out.push({ name: `${round}_${name}`, program: `dogfood/${round}/${f}`, renders: "dogfood/renders", caption: `${round.replace("-", " ")}: ${caption(join(dir, round, f))}`, report: existsSync(resolve(ROOT, report)) ? report : undefined });
    }
  }
  return out;
}

function gallery(): string {
  // Links carry the site's base (a project page lives under /aixle/); images are relative so Vite bundles them.
  const base = (process.env.PAGES_BASE ?? "/aixle/").replace(/\/?$/, "/");
  const repo = "https://github.com/tyevco/aixle/blob/main";
  const lines: string[] = [
    "---",
    "title: Gallery",
    "---",
    "",
    "# Gallery",
    "",
    "Every example and every dogfooding model, as the tool renders them: the",
    "beauty render and the contact sheet, with the program that made it and a",
    "viewer that orbits the mesh in the browser. The renders are the committed",
    "ones, regenerated by CI from the programs; the viewers are built with the",
    "site. This page is generated by `npm run pages:gallery`.",
    "",
    "[[toc]]",
    "",
  ];
  const section = (title: string, intro: string, models: Model[]) => {
    lines.push(`## ${title}`, "", intro, "");
    for (const m of models) {
      lines.push(`### ${m.name}`, "", m.caption, "");
      lines.push(`![${m.name}, beauty render](../${m.renders}/${m.name}_beauty.png) ![${m.name}, contact sheet](../${m.renders}/${m.name}.png)`, "");
      const links = [`[program](${repo}/${m.program})`, `<a href="${base}viewers/${m.name}.html" target="_blank" rel="noopener">viewer</a>`];
      if (m.report) links.push(`[the agent's report](../${m.report})`);
      lines.push(links.join(" · "), "");
    }
  };
  section("Examples", "The worked models under `examples/`, each written to exercise a part of the language.", examples());
  section("Dogfooding", "Models built by fresh agents from the docs alone, kept as they wrote them, with their reports. See [the exercise](../dogfood/README.md).", dogfood());
  return lines.join("\n");
}

function viewers(): void {
  const out = resolve(ROOT, ".vitepress", "public", "viewers");
  mkdirSync(out, { recursive: true });
  for (const m of [...examples(), ...dogfood()]) {
    const tmp = join(tmpdir(), `aixle-viewer-${m.name}`);
    rmSync(tmp, { recursive: true, force: true });
    const t0 = performance.now();
    // A viewer page carries its GLB and texture inline; 96 cells and a 256 px atlas keep the largest models near 8 MB
    // (measured: 112 cells and 512 px gave 127 MB for 25 models, the trophy's lettering alone 12.5 MB).
    run(readFileSync(resolve(ROOT, m.program), "utf8"), m.program, tmp, {
      defaultGrid: 96,
      views: [],
      steps: false,
      slices: false,
      turntable: false,
      obj: false,
      beauty: false,
      texture: 256,
    });
    copyFileSync(join(tmp, "viewer.html"), join(out, `${m.name}.html`));
    console.log(`${m.name.padEnd(10)} viewer ${((performance.now() - t0) / 1000).toFixed(1)}s  ${(statSync(join(out, `${m.name}.html`)).size / 1024 / 1024).toFixed(1)} MB`);
    rmSync(tmp, { recursive: true, force: true });
  }
}

if (process.argv.includes("--viewers")) viewers();
else {
  writeFileSync(resolve(ROOT, "docs", "gallery.md"), gallery());
  console.log("wrote docs/gallery.md");
}
