/** The language reference, generated from the builtin signatures so it cannot drift. */
import { BUILTINS } from "./lang/builtins.js";
import { signature } from "./lang/interpreter.js";
import { PRESETS, PATTERNS } from "./sdf/materials.js";
import { ROBLOX_LIMITS } from "./export/roblox.js";

export function referenceMarkdown(): string {
  const groups = new Map<string, typeof BUILTINS>();
  for (const b of BUILTINS) {
    let g = groups.get(b.group);
    if (!g) groups.set(b.group, (g = []));
    g.push(b);
  }
  const out: string[] = [
    "# Aixle reference",
    "",
    "Generated by `npm run docs` from the builtin signatures. Do not edit by hand; see `docs/language.md` for the language itself.",
    "",
    "Arguments are positional or by name (`cylinder(r=1, h=2)`); `name=value` in a signature is a default. `shape` is a 3D shape, `shape2` a 2D profile, `curve` a bezier() or curve(). Angles are degrees. `a | f(x)` means `f(a, x)`.",
    "",
  ];
  for (const [group, items] of groups) {
    out.push(`## ${group}`, "");
    for (const b of items) {
      out.push(`### ${b.name}`, "", b.doc, "");
      for (const ov of b.overloads) out.push(`    ${signature(b.name, ov)}`);
      const docs = b.overloads.flatMap((ov) => ov.params.filter((p) => p.doc).map((p) => `- \`${p.name}\`: ${p.doc}`));
      if (docs.length) out.push("", ...[...new Set(docs)]);
      out.push("");
    }
  }
  out.push(
    "## Files",
    "",
    "### import",
    "",
    "An existing mesh as a shape: `import(\"part.obj\")` or a `.glb`, relative to the program's folder. The mesh is sampled into a distance field over a grid of `resolution` cells on its longest side (default 96), so it can be cut, blended, hollowed and painted like any shape; `size=` scales its longest side to that many units. Closed meshes work; an open mesh has no inside and the report says so.",
    "",
    "    import(path, size=?, resolution=96) -> shape",
    "",
    "### use",
    "",
    "A library's defs and constants under a prefix: `use \"parts/hardware.aix\"` (relative to the program) or `use \"std/furniture\" as f` (shipped with the tool: std/hardware, std/furniture, std/plants). Then `hardware.hex_bolt(0.1, 0.6)` or `f.chair(seat=0.45)`. The library runs on its own: its defs see its own helpers and constants, its shapes stay its own, and `aixle doc lib.aix` prints what it offers.",
    "",
    "    use \"path\" [as name]",
    "",
  );
  out.push(
    "## Poses and animation",
    "",
    "### joint",
    "",
    "Make a part turn about a pivot under poses: `joint(part, \"elbow\", x, y, z)` with the pivot in world units, declared once the part is in place; combine it with `+` and `paint` afterwards, not `move`. Nested joints turn with their parent. With `axis=[x, y, z]` the joint turns about that one direction through the pivot (a raked steering column) and a pose gives it a single angle. Exports get a node per joint and glTF animations from animation().",
    "",
    "    joint(part, name, x, y, z) -> shape",
    "    joint(part, name, x, y, z, axis=[ax, ay, az]) -> shape",
    "",
    "### pose",
    "",
    "Name a set of joint angles: `pose(\"wave\", shoulder=[0, 0, 70], elbow=[0, 0, 40])`, degrees about x, y, z per joint, or one number for a joint declared with axis=. A joint can also move and scale: `pose(\"hop\", body=xform(move=[0, 0.3, 0], scale=[1, 1.1, 1]))` (see xform under Assembly; scale is about the pivot, then the turn, then the move). Joints not named stay at rest; `from=\"reach\"` starts from another pose's joints, so `pose(\"hold\", from=\"reach\", finger_l=xform(move=[0.03, 0, 0]))` is the reach with a finger closed. Every pose is drawn on `poses.png`; `set pose wave` makes the sheet and exports show it.",
    "",
    "    pose(name, joint=[x, y, z], ...) -> string",
    "    pose(name, joint=xform(rotate=[x, y, z], move=[dx, dy, dz], scale=[sx, sy, sz]), ...) -> string",
    "    pose(name, from=\"other\", joint=..., ...) -> string",
    "",
    "### animation",
    "",
    "A glTF animation from poses: `animation(\"wave\", [\"rest\", \"wave\", \"rest\"], seconds=1.2)`; keyframes are spaced evenly and interpolate linearly. `times=[0, 0.2, 1.2]` puts each pose at its own second instead (the last is the length, so leave seconds out); `ease=1` slows to a stop at every pose (0 is linear, between is a blend), which the GLB carries as a few keys per segment; `ease_ends=0` leaves the first and last pose alone, so a loop runs through its seam (a two-key clip has no pose between, so a one-shot that should settle holds its last pose as a third key). `loop=0` is a one-shot. A rest pose is any pose with no angles, or the name \"rest\". Each animation gets a frame strip `anim_<name>.png`, and the viewer page plays them with loop, speed and a scrub bar.",
    "",
    "    animation(name, poses, seconds=1, loop=1, ease=0, ease_ends=ease) -> string",
    "    animation(name, poses, times=[0, ...], loop=1, ease=0, ease_ends=ease) -> string",
    "",
  );
  out.push(
    "## Lights, cameras and environments",
    "",
    "The beauty render's lighting and shots, declared in the program. Without a `light()` the render has one key light, placed by `set light_azimuth`, `set light_elevation` and `set light_size`.",
    "",
    "### light",
    "",
    "A light in the beauty render: `light(\"key\", azimuth=-40, elevation=55, size=1.5, color=\"#fff2e0\")` and `light(\"rim\", azimuth=150, elevation=20, power=0.5, color=\"#cfe0ff\")`. Azimuth is degrees about y (0 from the front, +z; 90 from +x), elevation above the floor; `size` is the light's apparent size (0.5 a lamp with crisp shadows, 3 a window); `color` is a colour name, a hex or a material; `power` is its strength, 1 being the default key light's. Each light casts its own soft shadow, so three lights cost about half again the time of one (measured on the market scene: 4.1 s to 5.9 s at 512 px). The first `light()` replaces the default key light; declare as many as the picture needs. The report lists them.",
    "",
    "    light(name, azimuth=-40, elevation=55, size=1, color=\"white\", power=1) -> string",
    "",
    "### camera",
    "",
    "A named shot: `camera(\"hero\", azimuth=30, elevation=20, zoom=1.4)` and `camera(\"detail\", focus=\"nameplate\", zoom=2)`. `render --beauty` writes `beauty_<name>.png` for each, framed on `focus=` (a step or object, as `--focus` frames it) when given, with the render's own azimuth, elevation, zoom and dof for whatever a shot leaves out. `set camera hero` makes that shot the sheet's and `beauty.png`'s view too (the command line's `--azimuth`, `--elevation` and `--zoom` still override).",
    "",
    "    camera(name, azimuth=35, elevation=25, zoom=1, focus=\"step\", dof=0) -> string",
    "",
    "### set environment",
    "",
    "The sky the beauty render sits in and the metals reflect: `set environment sunset`. `studio` (the default) is the grey-white backdrop; `overcast` a white sky with soft, even light; `sunset` a warm band at the horizon under a blue sky on warm ground; `night` a dark blue sky and a dark floor, where a `glow` material carries the picture. An environment sets the sky, ground and floor colours and scales the ambient light; the lights are yours.",
    "",
  );
  out.push("## Roblox attachments", "", "An `anchor` with one of these names becomes the accessory's attachment in `model.roblox.glb` (`set roblox 1`), and the report checks the model against the size limit for it at the Normal body scale, in studs (width × height × depth).", "", "| Attachment | Kind | Limit |", "| --- | --- | --- |");
  for (const [name, lim] of Object.entries(ROBLOX_LIMITS)) out.push(`| ${name} | ${lim.kind} | ${lim.size.join(" × ")} |`);
  out.push("");
  out.push("## Material presets", "", "Use any of these by name in `paint()`. A colour name (`\"red\"`) or hex (`\"#c8342a\"`) also works.", "");
  out.push(
    "| Name | Pattern | Feature size | Colours | Notes |",
    "| --- | --- | --- | --- | --- |",
  );
  for (const m of PRESETS.values()) {
    const hex = (c: number[]) => "#" + c.map((v) => Math.round(v * 255).toString(16).padStart(2, "0")).join("");
    const notes = [m.metal ? "metal" : "", m.transmit ? `glass (transmit ${m.transmit})` : "", `rough ${m.rough}`].filter(Boolean).join(", ");
    out.push(`| ${m.name} | ${m.pattern} | ${m.pattern === "solid" ? "" : `${m.scale} units`} | ${hex(m.color)}${m.pattern !== "solid" ? " / " + hex(m.color2) : ""} | ${notes} |`);
  }
  out.push("", "A pattern's feature size is in model units: a wood ring every 0.25 units suits a table leg, not a 20-unit floor. Use `material(color, pattern, color2, scale=)` with the two colours from this table for the same look at another size.");
  out.push("", "## Patterns", "", `For \`material(color, pattern, ...)\`: ${PATTERNS.join(", ")}.`, "");
  return out.join("\n");
}
