/** The language reference, generated from the builtin signatures so it cannot drift. */
import { BUILTINS } from "./lang/builtins.js";
import { signature } from "./lang/interpreter.js";
import { PRESETS, PATTERNS } from "./sdf/materials.js";

export function referenceMarkdown(): string {
  const groups = new Map<string, typeof BUILTINS>();
  for (const b of BUILTINS) {
    let g = groups.get(b.group);
    if (!g) groups.set(b.group, (g = []));
    g.push(b);
  }
  const out: string[] = [
    "# Aixle reference",
    "",
    "Generated by `npm run docs` from the builtin signatures. Do not edit by hand; see `docs/language.md` for the language itself.",
    "",
    "Arguments are positional or by name (`cylinder(r=1, h=2)`); `name=value` in a signature is a default. `shape` is a 3D shape, `shape2` a 2D profile, `curve` a bezier() or curve(). Angles are degrees. `a | f(x)` means `f(a, x)`.",
    "",
  ];
  for (const [group, items] of groups) {
    out.push(`## ${group}`, "");
    for (const b of items) {
      out.push(`### ${b.name}`, "", b.doc, "");
      for (const ov of b.overloads) out.push(`    ${signature(b.name, ov)}`);
      const docs = b.overloads.flatMap((ov) => ov.params.filter((p) => p.doc).map((p) => `- \`${p.name}\`: ${p.doc}`));
      if (docs.length) out.push("", ...[...new Set(docs)]);
      out.push("");
    }
  }
  out.push(
    "## Files",
    "",
    "### import",
    "",
    "An existing mesh as a shape: `import(\"part.obj\")` or a `.glb`, relative to the program's folder. The mesh is sampled into a distance field over a grid of `resolution` cells on its longest side (default 96), so it can be cut, blended, hollowed and painted like any shape; `size=` scales its longest side to that many units. Closed meshes work; an open mesh has no inside and the report says so.",
    "",
    "    import(path, size=?, resolution=96) -> shape",
    "",
  );
  out.push(
    "## Poses and animation",
    "",
    "### joint",
    "",
    "Make a part turn about a pivot under poses: `joint(part, \"elbow\", x, y, z)` with the pivot in world units, declared once the part is in place; combine it with `+` and `paint` afterwards, not `move`. Nested joints turn with their parent. Exports get a node per joint and glTF animations from animation().",
    "",
    "    joint(part, name, x, y, z) -> shape",
    "",
    "### pose",
    "",
    "Name a set of joint angles: `pose(\"wave\", shoulder=[0, 0, 70], elbow=[0, 0, 40])`, degrees about x, y, z per joint. Joints not named stay at rest. Every pose is drawn on `poses.png`; `set pose wave` makes the sheet and exports show it.",
    "",
    "    pose(name, joint=[x, y, z], ...) -> string",
    "",
    "### animation",
    "",
    "A glTF animation from poses: `animation(\"wave\", [\"rest\", \"wave\", \"rest\"], seconds=1.2)`; keyframes are spaced evenly and interpolate linearly. A rest pose is any pose with no angles, or the name \"rest\". Each animation gets a frame strip `anim_<name>.png`.",
    "",
    "    animation(name, poses, seconds=1, loop=1) -> string",
    "",
  );
  out.push("## Material presets", "", "Use any of these by name in `paint()`. A colour name (`\"red\"`) or hex (`\"#c8342a\"`) also works.", "");
  out.push(
    "| Name | Pattern | Feature size | Colours | Notes |",
    "| --- | --- | --- | --- | --- |",
  );
  for (const m of PRESETS.values()) {
    const hex = (c: number[]) => "#" + c.map((v) => Math.round(v * 255).toString(16).padStart(2, "0")).join("");
    const notes = [m.metal ? "metal" : "", m.transmit ? `glass (transmit ${m.transmit})` : "", `rough ${m.rough}`].filter(Boolean).join(", ");
    out.push(`| ${m.name} | ${m.pattern} | ${m.pattern === "solid" ? "" : `${m.scale} units`} | ${hex(m.color)}${m.pattern !== "solid" ? " / " + hex(m.color2) : ""} | ${notes} |`);
  }
  out.push("", "A pattern's feature size is in model units: a wood ring every 0.25 units suits a table leg, not a 20-unit floor. Use `material(color, pattern, color2, scale=)` with the two colours from this table for the same look at another size.");
  out.push("", "## Patterns", "", `For \`material(color, pattern, ...)\`: ${PATTERNS.join(", ")}.`, "");
  return out.join("\n");
}
